const data = {
  // users: [
  //   {
  //     name: "Ivo Legzdins",
  //     //email: "ilegzdins@yahoo.com",
  //     status: "allowed",
  //     isAdmin: true,
  //     //profileImage:
  //     // "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10159188245624807&height=50&width=50&ext=1634916442&hash=AeTL3m3bSlGyfGIGRrY",
  //   },

  //   {
  //     name: "Ivo Test",
  //     //email: "test@pending.co.uk",
  //     status: "pending",
  //     isAdmin: false,
  //     // profileImage:
  //     //   "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10159188245624807&height=50&width=50&ext=1634916442&hash=AeTL3m3bSlGyfGIGRrY",
  //   },
  //   {
  //     name: "Ivo Test2",
  //     // email: "test@blocked.co.uk",
  //     status: "blocked",
  //     isAdmin: false,
  //     //profileImage:
  //     //  "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10159188245624807&height=50&width=50&ext=1634916442&hash=AeTL3m3bSlGyfGIGRrY",
  //   },
  // ],

  // products: [
  //   {
  //     id: 1,
  //     slug: "sheffield-home-kids",
  //     name: "Sheffield Home Kids",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 2,
  //     slug: "orlando-pirates",
  //     name: "Orlando Pirates",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 3,
  //     slug: "chelsea-away-women",
  //     name: "Chelsea Away Women",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 4,
  //     slug: "middlesbrough-away",
  //     name: "Middlesbrough Away",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 5,
  //     slug: "beko-polo",
  //     name: "Beko Polo",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 6,
  //     slug: "2020-belgium-way-soccer",
  //     name: "2020 Belgium Away Soccer",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 7,
  //     slug: "sheffield-home-kidss",
  //     name: "Sheffield Home Kidss",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 8,
  //     slug: "orlando-piratess",
  //     name: "Orlando Piratess",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 9,
  //     slug: "chelsea-away-womens",
  //     name: "Chelsea Away Womens",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 10,
  //     slug: "middlesbrough-aways",
  //     name: "Middlesbrough Aways",
  //     category: ["adult kit"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 11,
  //     slug: "beko-polos",
  //     name: "Beko Polos",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 12,
  //     slug: "2020-belgium-way-soccers",
  //     name: "2020 Belgium Away Soccers",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 13,
  //     slug: "sheffield-home-kidsee",
  //     name: "Sheffield Home Kidsee",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 14,
  //     slug: "orlando-piratesee",
  //     name: "Orlando Piratesee",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 15,
  //     slug: "chelsea-away-womenee",
  //     name: "Chelsea Away Womenee",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 16,
  //     slug: "middlesbrough-awayee",
  //     name: "Middlesbrough Awayee",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 17,
  //     slug: "beko-poloee",
  //     name: "Beko Poloee",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 18,
  //     slug: "2020-belgium-way-socceree",
  //     name: "2020 Belgium Away Socceree",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 19,
  //     slug: "sheffield-home-kidssee",
  //     name: "Sheffield Home Kidssee",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 20,
  //     slug: "orlando-piratessee",
  //     name: "Orlando Piratessee",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 21,
  //     slug: "chelsea-away-womensee",
  //     name: "Chelsea Away Womensee",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 22,
  //     slug: "middlesbrough-awaysee",
  //     name: "Middlesbrough Awaysee",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 23,
  //     slug: "beko-polosee",
  //     name: "Beko Polosee",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 24,
  //     slug: "2020-belgium-way-soccersee",
  //     name: "2020 Belgium Away Soccersee",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 25,
  //     slug: "sheffield-home-kidsrr",
  //     name: "Sheffield Home Kidsrr",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 26,
  //     slug: "orlando-piratesrr",
  //     name: "Orlando Piratesrr",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 27,
  //     slug: "chelsea-away-womenrr",
  //     name: "Chelsea Away Womenrr",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 28,
  //     slug: "middlesbrough-awayrr",
  //     name: "Middlesbrough Awayrr",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 29,
  //     slug: "beko-polorr",
  //     name: "Beko Polorr",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 30,
  //     slug: "2020-belgium-way-soccerrr",
  //     name: "2020 Belgium Away Soccerrr",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 31,
  //     slug: "sheffield-home-kidssrr",
  //     name: "Sheffield Home Kidssrr",
  //     category: ["Kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 32,
  //     slug: "orlando-piratessrr",
  //     name: "Orlando Piratessrr",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 33,
  //     slug: "chelsea-away-womensrr",
  //     name: "Chelsea Away Womensrr",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 34,
  //     slug: "middlesbrough-awaysrr",
  //     name: "Middlesbrough Awaysrr",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 35,
  //     slug: "beko-polosrr",
  //     name: "Beko Polosrr",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 36,
  //     slug: "2020-belgium-way-soccersrr",
  //     name: "2020 Belgium Away Soccersrr",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 37,
  //     slug: "sheffield-home-kidseerr",
  //     name: "Sheffield Home Kidseerr",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 38,
  //     slug: "orlando-pirateseerr",
  //     name: "Orlando Pirateseerr",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 39,
  //     slug: "chelsea-away-womeneerr",
  //     name: "Chelsea Away Womeneerr",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 40,
  //     slug: "middlesbrough-awayeerr",
  //     name: "Middlesbrough Awayeerr",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 41,
  //     slug: "beko-poloeerr",
  //     name: "Beko Poloeerr",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 42,
  //     slug: "2020-belgium-way-soccereerr",
  //     name: "2020 Belgium Away Soccereerr",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  //   {
  //     id: 43,
  //     slug: "sheffield-home-kidsseerr",
  //     name: "Sheffield Home Kidsseerr",
  //     category: ["kids kit"],
  //     images: [{ src: "/shirt1_kqwsvm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],
  //     price: 70,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 44,
  //     slug: "orlando-piratesseerr",
  //     name: "Orlando Piratesseerr",
  //     category: ["usa"],
  //     images: [{ src: "/shirt2_glujuz" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 80,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 45,
  //     slug: "chelsea-away-womenseerr",
  //     name: "Chelsea Away Womenseerr",
  //     category: ["women jerseys"],
  //     images: [{ src: "/shirt3_liklyt" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "A popular shirt",
  //   },
  //   {
  //     id: 46,
  //     slug: "middlesbrough-awayseerr",
  //     name: "Middlesbrough Awayseerr",
  //     category: ["a"],
  //     images: [{ src: "/shirt4_ilm4sm" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 90,
  //     description: "Latest shirt",
  //   },
  //   {
  //     id: 47,
  //     slug: "beko-poloseerr",
  //     name: "Beko Poloseerr",
  //     category: ["uk premier league"],
  //     images: [{ src: "/shirt5_stb1fb" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 95,
  //     description: "100% organic cotton",
  //   },
  //   {
  //     id: 48,
  //     slug: "2020-belgium-way-soccerseerr",
  //     name: "2020 Belgium Away Soccerseerr",
  //     category: ["uefa euro 2020"],
  //     images: [{ src: "/shirt6_jesndd" }, { src: "/shirt2_glujuz" }],
  //     sizes: [
  //       { name: "XXS", inStock: false },
  //       { name: "XS", inStock: true },
  //       { name: "S", inStock: true },
  //       { name: "M", inStock: true },
  //       { name: "L", inStock: true },
  //       { name: "XL", inStock: true },
  //       { name: "2XL", inStock: true },
  //       { name: "3XL", inStock: true },
  //     ],

  //     price: 75,
  //     description: "Last season",
  //   },
  // ],
  productCategories: [
    { name: "New jerseys", value: "new jerseys" },
    { name: "UEFA Euro 2020", value: "uefa euro 2020 jerseys" },
    { name: "UK Premier League", value: "uk premier legue" },
    { name: "France Ligue 1", value: "france ligue 1" },
    { name: "Mexico club", value: "mexico club" },
    { name: "Adult jacket", value: "adult jacket" },
    { name: "Long tracksuit", value: "long tracksuit" },
    { name: "Adult kit", value: "adult kit" },
    { name: "Baby jerseys", value: "baby jerseys" },
    { name: "National team jerseys", value: "national team jerseys" },
    { name: "Top quality other clubs", value: "Top quality other clubs" },
    { name: "Long sleeve", value: "long sleeves jerseys" },
    { name: "Italy Serie A", value: "italy serie a" },
    { name: "Spain La Liga", value: "spain la liga" },
    { name: "German Bundesliga", value: "german bundesliga" },
    { name: "MLS jersey", value: "mls jersey" },
    { name: "Hoodies jacket", value: "hoodies jacket" },
    { name: "Windbreaker", value: "windbreaker" },
    { name: "Kids kit", value: "kids kit" },
    { name: "Women jerseys", value: "women jerseys" },
    { name: "U", value: "曼 U" },
    { name: "Retro jerseys", value: "retro jerseys" },
    { name: "Player version jersey", value: "player version jersey" },
  ],
};
export default data;
